# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\hozhen\Google Drive\Docs Ho-Zhen\projects\UMBS\UMBS Project\Software\PSoC\Drivers\Decagon_Soilmoisture\Decagon_Soilmoisture.cydsn\Decagon_Soilmoisture.cyprj
# Date: Sun, 16 Nov 2014 22:11:17 GMT
#set_units -time ns
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {NEOMOTE_1_UART_MOTE_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 27 53} -nominal_period 1083.3333333333333 [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {NEOMOTE_1_Clock_1} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2001 4001} -nominal_period 83333.333333333328 [list [get_pins {ClockBlock/dclk_glb_1}]]
create_clock -name {NEOMOTE_1_Clock_1(fixed-function)} -period 83333.333333333328 -waveform {0 41.6666666666667} -nominal_period 83333.333333333328 [get_pins {ClockBlock/dclk_glb_ff_1}]
create_generated_clock -name {UART_SoilMoisture_Decagon_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2501 5001} -nominal_period 104166.66666666666 [list [get_pins {ClockBlock/dclk_glb_2}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_clock -name {CyBUS_CLK(fixed-function)} -period 41.666666666666664 -waveform {0 20.8333333333333} [get_pins {ClockBlock/clk_bus_glb_ff}]

set_false_path -from [get_pins {__ZERO__/q}]

# Component constraints for C:\Users\hozhen\Google Drive\Docs Ho-Zhen\projects\UMBS\UMBS Project\Software\PSoC\Drivers\Decagon_Soilmoisture\Decagon_Soilmoisture.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\hozhen\Google Drive\Docs Ho-Zhen\projects\UMBS\UMBS Project\Software\PSoC\Drivers\Decagon_Soilmoisture\Decagon_Soilmoisture.cydsn\Decagon_Soilmoisture.cyprj
# Date: Sun, 16 Nov 2014 22:10:52 GMT
